export { License } from '@/components/feedstock/license'
export { Links } from '@/components/feedstock/links'
export { Maintainers } from '@/components/feedstock/maintainers'
export { Providers } from '@/components/feedstock/providers'
export { Stores } from '@/components/feedstock/stores'
export { Thumbnail } from '@/components/feedstock/thumbnail'
